"""
Static line, station, and color data for Tokyo rail network.
Covers all lines within/around the Yamanote Loop.
"""

# Line definitions: code → display info + ODPT API identifiers
LINES = {
    # JR East
    "JY": {"name": "Yamanote",       "short": "Yamanote", "color": "#9acd32", "text": "#000000", "shape": "square",  "operator": "JR-East",     "odpt": "odpt.Railway:JR-East.Yamanote"},
    "JC": {"name": "Chuo Rapid",     "short": "Chuo",     "color": "#f15a22", "text": "#ffffff", "shape": "square",  "operator": "JR-East",     "odpt": "odpt.Railway:JR-East.ChuoRapid"},
    "JB": {"name": "Chuo-Sobu",      "short": "Sobu",     "color": "#ffe200", "text": "#000000", "shape": "square",  "operator": "JR-East",     "odpt": "odpt.Railway:JR-East.ChuoSobuLocal"},
    "JK": {"name": "Keihin-Tohoku",  "short": "KeihinToh","color": "#00b2e3", "text": "#000000", "shape": "square",  "operator": "JR-East",     "odpt": "odpt.Railway:JR-East.KeihinTohokuNegishi"},
    "JA": {"name": "Saikyo",         "short": "Saikyo",   "color": "#f5a0bf", "text": "#000000", "shape": "square",  "operator": "JR-East",     "odpt": "odpt.Railway:JR-East.Saikyo"},
    "JH": {"name": "Shonan-Shinjuku","short": "ShonanShj","color": "#22ac38", "text": "#ffffff", "shape": "square",  "operator": "JR-East",     "odpt": "odpt.Railway:JR-East.ShonanShinjuku"},
    "JU": {"name": "Utsunomiya/Takasaki","short": "Utsu/Taka","color": "#f68b1f","text": "#ffffff","shape": "square", "operator": "JR-East",    "odpt": "odpt.Railway:JR-East.UtsunomiyaTakasaki"},
    "JE": {"name": "Keiyo",          "short": "Keiyo",    "color": "#dc143c", "text": "#ffffff", "shape": "square",  "operator": "JR-East",     "odpt": "odpt.Railway:JR-East.Keiyo"},
    "JO": {"name": "Yokosuka/Sobu",  "short": "Yokosuka", "color": "#0068b7", "text": "#ffffff", "shape": "square",  "operator": "JR-East",     "odpt": "odpt.Railway:JR-East.Yokosuka"},
    # Tokyo Metro
    "G":  {"name": "Ginza",          "short": "Ginza",    "color": "#f39700", "text": "#000000", "shape": "circle",  "operator": "TokyoMetro",  "odpt": "odpt.Railway:TokyoMetro.Ginza"},
    "M":  {"name": "Marunouchi",     "short": "Marunouchi","color": "#e60012","text": "#ffffff", "shape": "circle",  "operator": "TokyoMetro",  "odpt": "odpt.Railway:TokyoMetro.Marunouchi"},
    "H":  {"name": "Hibiya",         "short": "Hibiya",   "color": "#9caeb7", "text": "#000000", "shape": "circle",  "operator": "TokyoMetro",  "odpt": "odpt.Railway:TokyoMetro.Hibiya"},
    "T":  {"name": "Tozai",          "short": "Tozai",    "color": "#00a7d8", "text": "#000000", "shape": "circle",  "operator": "TokyoMetro",  "odpt": "odpt.Railway:TokyoMetro.Tozai"},
    "C":  {"name": "Chiyoda",        "short": "Chiyoda",  "color": "#00a651", "text": "#ffffff", "shape": "circle",  "operator": "TokyoMetro",  "odpt": "odpt.Railway:TokyoMetro.Chiyoda"},
    "Y":  {"name": "Yurakucho",      "short": "Yurakucho","color": "#c9a800", "text": "#000000", "shape": "circle",  "operator": "TokyoMetro",  "odpt": "odpt.Railway:TokyoMetro.Yurakucho"},
    "Z":  {"name": "Hanzomon",       "short": "Hanzomon", "color": "#8f76d6", "text": "#ffffff", "shape": "circle",  "operator": "TokyoMetro",  "odpt": "odpt.Railway:TokyoMetro.Hanzomon"},
    "N":  {"name": "Namboku",        "short": "Namboku",  "color": "#00ac9b", "text": "#000000", "shape": "circle",  "operator": "TokyoMetro",  "odpt": "odpt.Railway:TokyoMetro.Namboku"},
    "F":  {"name": "Fukutoshin",     "short": "Fukutoshin","color": "#9c5e31","text": "#ffffff", "shape": "circle",  "operator": "TokyoMetro",  "odpt": "odpt.Railway:TokyoMetro.Fukutoshin"},
    # Toei
    "A":  {"name": "Toei Asakusa",   "short": "Asakusa",  "color": "#e85298", "text": "#ffffff", "shape": "rect",    "operator": "Toei",        "odpt": "odpt.Railway:Toei.Asakusa"},
    "I":  {"name": "Toei Mita",      "short": "Mita",     "color": "#006cb1", "text": "#ffffff", "shape": "rect",    "operator": "Toei",        "odpt": "odpt.Railway:Toei.Mita"},
    "S":  {"name": "Toei Shinjuku",  "short": "Shinjuku", "color": "#6cbb5a", "text": "#000000", "shape": "rect",    "operator": "Toei",        "odpt": "odpt.Railway:Toei.Shinjuku"},
    "E":  {"name": "Toei Oedo",      "short": "Oedo",     "color": "#b6007a", "text": "#ffffff", "shape": "rect",    "operator": "Toei",        "odpt": "odpt.Railway:Toei.Oedo"},
    # Private railways
    "TY": {"name": "Tokyu Toyoko",   "short": "Toyoko",   "color": "#e60012", "text": "#ffffff", "shape": "rect",    "operator": "Tokyu",       "odpt": "odpt.Railway:Tokyu.Toyoko"},
    "DT": {"name": "Tokyu Den-en",   "short": "Den-en",   "color": "#e87722", "text": "#ffffff", "shape": "rect",    "operator": "Tokyu",       "odpt": "odpt.Railway:Tokyu.DenEnToshi"},
    "OM": {"name": "Tokyu Oimachi",  "short": "Oimachi",  "color": "#30a832", "text": "#ffffff", "shape": "rect",    "operator": "Tokyu",       "odpt": "odpt.Railway:Tokyu.Oimachi"},
    "MG": {"name": "Tokyu Meguro",   "short": "Meguro",   "color": "#0099cb", "text": "#ffffff", "shape": "rect",    "operator": "Tokyu",       "odpt": "odpt.Railway:Tokyu.Meguro"},
    "IK": {"name": "Tokyu Ikegami",  "short": "Ikegami",  "color": "#f09820", "text": "#ffffff", "shape": "rect",    "operator": "Tokyu",       "odpt": "odpt.Railway:Tokyu.Ikegami"},
    "KO": {"name": "Keio",           "short": "Keio",     "color": "#4063b0", "text": "#ffffff", "shape": "rect",    "operator": "Keio",        "odpt": "odpt.Railway:Keio.Keio"},
    "KL": {"name": "Keio Sagamihara","short": "Keio-Sag", "color": "#4063b0", "text": "#ffffff", "shape": "rect",    "operator": "Keio",        "odpt": "odpt.Railway:Keio.Sagamihara"},
    "KI": {"name": "Keio Inokashira","short": "Inokashira","color": "#009f68","text": "#ffffff", "shape": "rect",    "operator": "Keio",        "odpt": "odpt.Railway:Keio.Inokashira"},
    "OH": {"name": "Odakyu Odawara", "short": "Odakyu",   "color": "#0074be", "text": "#ffffff", "shape": "rect",    "operator": "Odakyu",      "odpt": "odpt.Railway:Odakyu.Odawara"},
    "OE": {"name": "Odakyu Enoshima","short": "Enoshima", "color": "#0074be", "text": "#ffffff", "shape": "rect",    "operator": "Odakyu",      "odpt": "odpt.Railway:Odakyu.Enoshima"},
    "SI": {"name": "Seibu Ikebukuro","short": "Seibu-Ike","color": "#ffe200", "text": "#000000", "shape": "rect",    "operator": "Seibu",       "odpt": "odpt.Railway:Seibu.Ikebukuro"},
    "SS": {"name": "Seibu Shinjuku", "short": "Seibu-Shj","color": "#c40071", "text": "#ffffff", "shape": "rect",    "operator": "Seibu",       "odpt": "odpt.Railway:Seibu.Shinjuku"},
    "TJ": {"name": "Tobu Tojo",      "short": "Tobu-Tojo","color": "#007dc6", "text": "#ffffff", "shape": "rect",    "operator": "Tobu",        "odpt": "odpt.Railway:Tobu.Tojo"},
    "TS": {"name": "Tobu Skytree",   "short": "Skytree",  "color": "#f5a200", "text": "#000000", "shape": "rect",    "operator": "Tobu",        "odpt": "odpt.Railway:Tobu.TobuSkytreeLine"},
    "KS": {"name": "Keikyu",         "short": "Keikyu",   "color": "#e60012", "text": "#ffffff", "shape": "rect",    "operator": "Keikyu",      "odpt": "odpt.Railway:Keikyu.Main"},
    "KK": {"name": "Keikyu Airport", "short": "Keikyu-AP","color": "#e60012", "text": "#ffffff", "shape": "rect",    "operator": "Keikyu",      "odpt": "odpt.Railway:Keikyu.Airport"},
    "KE": {"name": "Keisei Main",    "short": "Keisei",   "color": "#e95383", "text": "#ffffff", "shape": "rect",    "operator": "Keisei",      "odpt": "odpt.Railway:Keisei.Main"},
    "MM": {"name": "Minatomirai",    "short": "Minatomir","color": "#0065ac", "text": "#ffffff", "shape": "circle",  "operator": "Minatomirai", "odpt": "odpt.Railway:Minatomirai.Minatomirai"},
    "SR": {"name": "Saitama Railway","short": "Saitama",  "color": "#ee86a1", "text": "#000000", "shape": "rect",    "operator": "SaitamaRailway","odpt": "odpt.Railway:SaitamaRailway.SaitamaRailway"},
    "RI": {"name": "Rinkai",         "short": "Rinkai",   "color": "#007bc0", "text": "#ffffff", "shape": "rect",    "operator": "TWR",         "odpt": "odpt.Railway:TWR.Rinkai"},
    "YU": {"name": "Yurikamome",     "short": "Yurikamome","color": "#00b9ef","text": "#000000", "shape": "rect",    "operator": "Yurikamome",  "odpt": "odpt.Railway:Yurikamome.Yurikamome"},
    "MO": {"name": "Tokyo Monorail", "short": "Monorail", "color": "#00a0e9", "text": "#ffffff", "shape": "rect",    "operator": "TokyoMonorail","odpt": "odpt.Railway:TokyoMonorail.TokyoMonorail"},
}

# Major stations with connecting lines and ODPT IDs
# Format: { id: { name_en, name_ja, lines: [code, ...], odpt_ids: {code: odpt_station_id} } }
STATIONS = {
    "tokyo":          {"name_en": "Tokyo",           "name_ja": "東京",      "lines": ["JY","JC","JK","JO","G","M","T","Z"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Tokyo","JC":"odpt.Station:JR-East.ChuoRapid.Tokyo","G":"odpt.Station:TokyoMetro.Ginza.Tokyo","M":"odpt.Station:TokyoMetro.Marunouchi.Tokyo"}},
    "kanda":          {"name_en": "Kanda",            "name_ja": "神田",      "lines": ["JY","JC","JK","G"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Kanda","G":"odpt.Station:TokyoMetro.Ginza.Kanda"}},
    "akihabara":      {"name_en": "Akihabara",        "name_ja": "秋葉原",    "lines": ["JY","JB","H","TS"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Akihabara","H":"odpt.Station:TokyoMetro.Hibiya.Akihabara"}},
    "okachimachi":    {"name_en": "Okachimachi",      "name_ja": "御徒町",    "lines": ["JY","JK","G"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Okachimachi"}},
    "ueno":           {"name_en": "Ueno",             "name_ja": "上野",      "lines": ["JY","JK","G","H","KE"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Ueno","G":"odpt.Station:TokyoMetro.Ginza.Ueno","H":"odpt.Station:TokyoMetro.Hibiya.Ueno"}},
    "uguisudani":     {"name_en": "Uguisudani",       "name_ja": "鶯谷",      "lines": ["JY","JK"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Uguisudani"}},
    "nippori":        {"name_en": "Nippori",          "name_ja": "日暮里",    "lines": ["JY","JK","KE"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Nippori"}},
    "nishinippori":   {"name_en": "Nishi-Nippori",    "name_ja": "西日暮里",  "lines": ["JY","JK","C"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.NishiNippori","C":"odpt.Station:TokyoMetro.Chiyoda.NishiNippori"}},
    "tabata":         {"name_en": "Tabata",           "name_ja": "田端",      "lines": ["JY","JK"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Tabata"}},
    "komagome":       {"name_en": "Komagome",         "name_ja": "駒込",      "lines": ["JY","N"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Komagome","N":"odpt.Station:TokyoMetro.Namboku.Komagome"}},
    "sugamo":         {"name_en": "Sugamo",           "name_ja": "巣鴨",      "lines": ["JY","I"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Sugamo","I":"odpt.Station:Toei.Mita.Sugamo"}},
    "otsuka":         {"name_en": "Otsuka",           "name_ja": "大塚",      "lines": ["JY"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Otsuka"}},
    "ikebukuro":      {"name_en": "Ikebukuro",        "name_ja": "池袋",      "lines": ["JY","JA","JU","TJ","SI","Y","F"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Ikebukuro","Y":"odpt.Station:TokyoMetro.Yurakucho.Ikebukuro","F":"odpt.Station:TokyoMetro.Fukutoshin.Ikebukuro"}},
    "mejiro":         {"name_en": "Mejiro",           "name_ja": "目白",      "lines": ["JY"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Mejiro"}},
    "takadanobaba":   {"name_en": "Takadanobaba",     "name_ja": "高田馬場",  "lines": ["JY","SS","T"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Takadanobaba","T":"odpt.Station:TokyoMetro.Tozai.Takadanobaba"}},
    "shinokubo":      {"name_en": "Shin-Okubo",       "name_ja": "新大久保",  "lines": ["JY"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.ShinOkubo"}},
    "shinjuku":       {"name_en": "Shinjuku",         "name_ja": "新宿",      "lines": ["JY","JC","JB","JA","JH","KO","OH","S","M","E"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Shinjuku","M":"odpt.Station:TokyoMetro.Marunouchi.Shinjuku","S":"odpt.Station:Toei.Shinjuku.Shinjuku","E":"odpt.Station:Toei.Oedo.Shinjuku"}},
    "yoyogi":         {"name_en": "Yoyogi",           "name_ja": "代々木",    "lines": ["JY","JB","S","E"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Yoyogi","S":"odpt.Station:Toei.Shinjuku.Yoyogi"}},
    "harajuku":       {"name_en": "Harajuku",         "name_ja": "原宿",      "lines": ["JY","C"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Harajuku"}},
    "shibuya":        {"name_en": "Shibuya",          "name_ja": "渋谷",      "lines": ["JY","JH","TY","DT","KO","G","Z","F","MM"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Shibuya","G":"odpt.Station:TokyoMetro.Ginza.Shibuya","Z":"odpt.Station:TokyoMetro.Hanzomon.Shibuya","F":"odpt.Station:TokyoMetro.Fukutoshin.Shibuya","TY":"odpt.Station:Tokyu.Toyoko.Shibuya","DT":"odpt.Station:Tokyu.DenEnToshi.Shibuya"}},
    "ebisu":          {"name_en": "Ebisu",            "name_ja": "恵比寿",    "lines": ["JY","JH","H"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Ebisu","H":"odpt.Station:TokyoMetro.Hibiya.Ebisu"}},
    "meguro":         {"name_en": "Meguro",           "name_ja": "目黒",      "lines": ["JY","TY","MG","I","N"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Meguro","N":"odpt.Station:TokyoMetro.Namboku.Meguro","I":"odpt.Station:Toei.Mita.Meguro","MG":"odpt.Station:Tokyu.Meguro.Meguro"}},
    "gotanda":        {"name_en": "Gotanda",          "name_ja": "五反田",    "lines": ["JY","IK","A"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Gotanda","A":"odpt.Station:Toei.Asakusa.Gotanda"}},
    "osaki":          {"name_en": "Osaki",            "name_ja": "大崎",      "lines": ["JY","JA","JH","RI"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Osaki","RI":"odpt.Station:TWR.Rinkai.Osaki"}},
    "shinagawa":      {"name_en": "Shinagawa",        "name_ja": "品川",      "lines": ["JY","JK","JH","KS","KK"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Shinagawa","KS":"odpt.Station:Keikyu.Main.Shinagawa"}},
    "tamachi":        {"name_en": "Tamachi",          "name_ja": "田町",      "lines": ["JY","JK","I"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Tamachi"}},
    "hamamatsucho":   {"name_en": "Hamamatsucho",     "name_ja": "浜松町",    "lines": ["JY","JK","MO","YU"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Hamamatsucho","YU":"odpt.Station:Yurikamome.Yurikamome.Hamamatsucho"}},
    "shimbashi":      {"name_en": "Shimbashi",        "name_ja": "新橋",      "lines": ["JY","JK","JO","G","A","YU"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Shimbashi","G":"odpt.Station:TokyoMetro.Ginza.Shimbashi","A":"odpt.Station:Toei.Asakusa.Shimbashi"}},
    "yurakucho":      {"name_en": "Yurakucho",        "name_ja": "有楽町",    "lines": ["JY","JK","Y","H"],
                       "odpt": {"JY":"odpt.Station:JR-East.Yamanote.Yurakucho","Y":"odpt.Station:TokyoMetro.Yurakucho.Yurakucho"}},
    # Additional key interchange stations
    "ueno-okachimachi": {"name_en": "Ueno-Okachimachi","name_ja": "上野御徒町","lines": ["E"],
                       "odpt": {"E":"odpt.Station:Toei.Oedo.Ueno-Okachimachi"}},
    "akasaka-mitsuke": {"name_en": "Akasaka-Mitsuke",  "name_ja": "赤坂見附",  "lines": ["G","M"],
                       "odpt": {"G":"odpt.Station:TokyoMetro.Ginza.AkasakaMitsuke","M":"odpt.Station:TokyoMetro.Marunouchi.AkasakaMitsuke"}},
    "omotesando":     {"name_en": "Omotesando",       "name_ja": "表参道",    "lines": ["G","C","Z"],
                       "odpt": {"G":"odpt.Station:TokyoMetro.Ginza.Omotesando","C":"odpt.Station:TokyoMetro.Chiyoda.Omotesando","Z":"odpt.Station:TokyoMetro.Hanzomon.Omotesando"}},
    "aoyama-itchome": {"name_en": "Aoyama-itchome",   "name_ja": "青山一丁目","lines": ["G","E"],
                       "odpt": {"G":"odpt.Station:TokyoMetro.Ginza.AoyamaItchome","E":"odpt.Station:Toei.Oedo.AoyamaItchome"}},
    "tameike-sanno":  {"name_en": "Tameike-Sanno",    "name_ja": "溜池山王",  "lines": ["G","N"],
                       "odpt": {"G":"odpt.Station:TokyoMetro.Ginza.TameikeS anno","N":"odpt.Station:TokyoMetro.Namboku.TameikeSanno"}},
    "ginza":          {"name_en": "Ginza",            "name_ja": "銀座",      "lines": ["G","M","H"],
                       "odpt": {"G":"odpt.Station:TokyoMetro.Ginza.Ginza","M":"odpt.Station:TokyoMetro.Marunouchi.Ginza","H":"odpt.Station:TokyoMetro.Hibiya.Ginza"}},
    "nihombashi":     {"name_en": "Nihombashi",       "name_ja": "日本橋",    "lines": ["G","T","A"],
                       "odpt": {"G":"odpt.Station:TokyoMetro.Ginza.Nihombashi","T":"odpt.Station:TokyoMetro.Tozai.Nihombashi","A":"odpt.Station:Toei.Asakusa.Nihombashi"}},
    "asakusa":        {"name_en": "Asakusa",          "name_ja": "浅草",      "lines": ["G","A","TS"],
                       "odpt": {"G":"odpt.Station:TokyoMetro.Ginza.Asakusa","A":"odpt.Station:Toei.Asakusa.Asakusa"}},
    "kasumigaseki":   {"name_en": "Kasumigaseki",     "name_ja": "霞ヶ関",    "lines": ["M","H","C"],
                       "odpt": {"M":"odpt.Station:TokyoMetro.Marunouchi.Kasumigaseki","H":"odpt.Station:TokyoMetro.Hibiya.Kasumigaseki","C":"odpt.Station:TokyoMetro.Chiyoda.Kasumigaseki"}},
    "kokkai-gijidomae": {"name_en": "Kokkai-Gijidomae","name_ja":"国会議事堂前","lines": ["M","C"],
                       "odpt": {"M":"odpt.Station:TokyoMetro.Marunouchi.KokkaiGijidomae","C":"odpt.Station:TokyoMetro.Chiyoda.KokkaiGijidomae"}},
    "otemachi":       {"name_en": "Otemachi",         "name_ja": "大手町",    "lines": ["M","T","C","Z","I"],
                       "odpt": {"M":"odpt.Station:TokyoMetro.Marunouchi.Otemachi","T":"odpt.Station:TokyoMetro.Tozai.Otemachi","C":"odpt.Station:TokyoMetro.Chiyoda.Otemachi","Z":"odpt.Station:TokyoMetro.Hanzomon.Otemachi","I":"odpt.Station:Toei.Mita.Otemachi"}},
    "nakameguro":     {"name_en": "Nakameguro",       "name_ja": "中目黒",    "lines": ["H","TY"],
                       "odpt": {"H":"odpt.Station:TokyoMetro.Hibiya.Nakameguro","TY":"odpt.Station:Tokyu.Toyoko.Nakameguro"}},
    "naka-okachimachi": {"name_en": "Naka-Okachimachi","name_ja": "仲御徒町","lines": ["H"],
                       "odpt": {"H":"odpt.Station:TokyoMetro.Hibiya.NakaOkachimachi"}},
    "tsukiji":        {"name_en": "Tsukiji",          "name_ja": "築地",      "lines": ["H"],
                       "odpt": {"H":"odpt.Station:TokyoMetro.Hibiya.Tsukiji"}},
    "nishi-shinjuku": {"name_en": "Nishi-Shinjuku",   "name_ja": "西新宿",    "lines": ["M","E"],
                       "odpt": {"M":"odpt.Station:TokyoMetro.Marunouchi.NishiShinjuku","E":"odpt.Station:Toei.Oedo.NishiShinjuku"}},
    "shinjuku-sanchome": {"name_en": "Shinjuku 3-chome","name_ja": "新宿三丁目","lines": ["M","F","S"],
                       "odpt": {"M":"odpt.Station:TokyoMetro.Marunouchi.Shinjuku3chome","F":"odpt.Station:TokyoMetro.Fukutoshin.Shinjuku3chome","S":"odpt.Station:Toei.Shinjuku.Shinjuku3chome"}},
    "shinjuku-gyoenmae": {"name_en": "Shinjuku-Gyoenmae","name_ja":"新宿御苑前","lines": ["M"],
                       "odpt": {"M":"odpt.Station:TokyoMetro.Marunouchi.ShinjukuGyoenmae"}},
    "yotsuya":        {"name_en": "Yotsuya",          "name_ja": "四ツ谷",    "lines": ["M","C"],
                       "odpt": {"M":"odpt.Station:TokyoMetro.Marunouchi.Yotsuya","C":"odpt.Station:TokyoMetro.Chiyoda.Yotsuya"}},
    "ichigaya":       {"name_en": "Ichigaya",         "name_ja": "市ケ谷",    "lines": ["Y","N","A","JB","JO"],
                       "odpt": {"Y":"odpt.Station:TokyoMetro.Yurakucho.Ichigaya","N":"odpt.Station:TokyoMetro.Namboku.Ichigaya","A":"odpt.Station:Toei.Asakusa.Ichigaya"}},
    "iidabashi":      {"name_en": "Iidabashi",        "name_ja": "飯田橋",    "lines": ["Y","N","E","A","T"],
                       "odpt": {"Y":"odpt.Station:TokyoMetro.Yurakucho.Iidabashi","N":"odpt.Station:TokyoMetro.Namboku.Iidabashi","E":"odpt.Station:Toei.Oedo.Iidabashi","A":"odpt.Station:Toei.Asakusa.Iidabashi"}},
    "kotake-mukaihara": {"name_en": "Kotake-Mukaihara","name_ja": "小竹向原","lines": ["Y","F"],
                       "odpt": {"Y":"odpt.Station:TokyoMetro.Yurakucho.KotakeMukaihara","F":"odpt.Station:TokyoMetro.Fukutoshin.KotakeMukaihara"}},
    "shimokitazawa":  {"name_en": "Shimokitazawa",    "name_ja": "下北沢",    "lines": ["OH","KI"],
                       "odpt": {"OH":"odpt.Station:Odakyu.Odawara.Shimokitazawa","KI":"odpt.Station:Keio.Inokashira.Shimokitazawa"}},
    "sangenjaya":     {"name_en": "Sangenjaya",       "name_ja": "三軒茶屋",  "lines": ["DT","S"],
                       "odpt": {"DT":"odpt.Station:Tokyu.DenEnToshi.Sangenjaya","S":"odpt.Station:Toei.Shinjuku.Sangenjaya"}},
    "gaienmae":       {"name_en": "Gaienmae",         "name_ja": "外苑前",    "lines": ["G"],
                       "odpt": {"G":"odpt.Station:TokyoMetro.Ginza.Gaienmae"}},
    "jiyugaoka":      {"name_en": "Jiyugaoka",        "name_ja": "自由が丘",  "lines": ["TY","OM"],
                       "odpt": {"TY":"odpt.Station:Tokyu.Toyoko.Jiyugaoka","OM":"odpt.Station:Tokyu.Oimachi.Jiyugaoka"}},
    "futako-tamagawa": {"name_en": "Futako-Tamagawa", "name_ja": "二子玉川",  "lines": ["DT","OM"],
                       "odpt": {"DT":"odpt.Station:Tokyu.DenEnToshi.FutakoTamagawa","OM":"odpt.Station:Tokyu.Oimachi.FutakoTamagawa"}},
    "osaki-hirokoji": {"name_en": "Osaki-Hirokoji",   "name_ja": "大崎広小路","lines": ["IK"],
                       "odpt": {"IK":"odpt.Station:Tokyu.Ikegami.OsakiHirokoji"}},
    "nishi-magome":   {"name_en": "Nishi-Magome",     "name_ja": "西馬込",    "lines": ["A"],
                       "odpt": {"A":"odpt.Station:Toei.Asakusa.NishiMagome"}},
    "haneda-airport": {"name_en": "Haneda Airport",   "name_ja": "羽田空港",  "lines": ["KK","MO"],
                       "odpt": {"KK":"odpt.Station:Keikyu.Airport.HanedaAirportT1T2","MO":"odpt.Station:TokyoMonorail.TokyoMonorail.HanedaAirportT1"}},
    "narita-airport": {"name_en": "Narita Airport",   "name_ja": "成田空港",  "lines": ["KE"],
                       "odpt": {"KE":"odpt.Station:Keisei.Main.NaritaAirportTerminal1"}},
    "yokohama":       {"name_en": "Yokohama",         "name_ja": "横浜",      "lines": ["JK","JO","KS","TY","MM","SR"],
                       "odpt": {"JK":"odpt.Station:JR-East.KeihinTohokuNegishi.Yokohama","KS":"odpt.Station:Keikyu.Main.Yokohama","TY":"odpt.Station:Tokyu.Toyoko.Yokohama","MM":"odpt.Station:Minatomirai.Minatomirai.Yokohama"}},
}

# Yamanote loop station order (for line tracker mode)
YAMANOTE_ORDER = [
    "tokyo","kanda","akihabara","okachimachi","ueno","uguisudani","nippori",
    "nishinippori","tabata","komagome","sugamo","otsuka","ikebukuro","mejiro",
    "takadanobaba","shinokubo","shinjuku","yoyogi","harajuku","shibuya",
    "ebisu","meguro","gotanda","osaki","shinagawa","tamachi","hamamatsucho",
    "shimbashi","yurakucho"
]

# Station sequences per line (key stations only, enough for tracker)
LINE_STATION_SEQUENCES = {
    "JY": YAMANOTE_ORDER,
    "G": ["shibuya","omotesando","gaienmae","aoyama-itchome","akasaka-mitsuke","tameike-sanno","toranomon","shimbashi","ginza","kyobashi","nihombashi","mitsukoshimae","kanda","suehirocho","ueno","naka-okachimachi","ueno","inaricho","tawaramachi","asakusa"],
    "M": ["ogikubo","minami-asagaya","shin-koenji","higashi-koenji","shin-nakano","nakano-sakaue","nishi-shinjuku","shinjuku","shinjuku-gyoenmae","shinjuku-sanchome","yotsuya-sanchome","yotsuya","akasaka-mitsuke","kokkai-gijidomae","kasumigaseki","ginza","tokyo","otemachi","awajicho","ochanomizu","hongo-sanchome","korakuen","myogadani","bunkyo","komagome","shin-otsuka","ikebukuro"],
    "H": ["nakameguro","ebisu","hiroo","roppongi","kamiyacho","kasumigaseki","hibiya","ginza","higashi-ginza","tsukiji","hatchobori","kayabacho","ningyocho","kodemmacho","akihabara","naka-okachimachi","iriya","minowa","minami-senju","kitasenju"],
    "Z": ["shibuya","omotesando","aoyama-itchome","nagatacho","hanzomon","kudanshita","jinbocho","otemachi","mitsukoshimae","oshiage"],
    "TY": ["shibuya","daikanyama","nakameguro","yutenji","gakugeidaigaku","togoshi-koen","musashi-koyama","jiyugaoka","toritsu-daigaku","midorigaoka","ookayama","senzoku","kohoku","kikuna","myorenji","hakuraku","higashi-hakuraku","tammachi","yokohama"],
    "DT": ["shibuya","ikejiri-ohashi","sangenjaya","komazawa-daigaku","sakurashinmachi","yoga","futako-tamagawa","futako-shinchi","takatsu","miyazakidai","miyamaedaira","saginuma","tana","nagatsuta","tsukushino","suzukakedai","minamimachida-grandberry-park","tsukimino","chuo-rinkan"],
    "OH": ["shinjuku","minami-shinjuku","sangubashi","yoyogi-hachiman","yoyogi-uehara","higashi-kitazawa","shimokitazawa","setagaya-daita","umegaoka","gotokuji","kyodo","soshigaya-okura","seijo-gakuenmae","kinuta","kami-kitazawa","shin-yurigaoka","odawara"],
}

# ODPT operator IDs
OPERATORS = {
    "JR-East":      "odpt.Operator:JR-East",
    "TokyoMetro":   "odpt.Operator:TokyoMetro",
    "Toei":         "odpt.Operator:Toei",
    "Tokyu":        "odpt.Operator:Tokyu",
    "Keio":         "odpt.Operator:Keio",
    "Odakyu":       "odpt.Operator:Odakyu",
    "Seibu":        "odpt.Operator:Seibu",
    "Tobu":         "odpt.Operator:Tobu",
    "Keikyu":       "odpt.Operator:Keikyu",
    "Keisei":       "odpt.Operator:Keisei",
    "Minatomirai":  "odpt.Operator:Minatomirai",
    "SaitamaRailway": "odpt.Operator:SaitamaRailway",
    "TWR":          "odpt.Operator:TWR",
    "Yurikamome":   "odpt.Operator:Yurikamome",
    "TokyoMonorail":"odpt.Operator:TokyoMonorail",
}
